spring:
  jpa:
    hibernate:
      ddl-auto: none
    #전송 쿼리 생성
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false
  datasource:
    url: ${MARIADB_LOCAL_URL}
    username: ${MARIADB_LOCAL_USER}
    password: ${MARIADB_LOCAL_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile
          kakao:
            client-id:
            redirect-uri:
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
            client_name: Kakao
        provider:
          kakao:
            authorization-uri: ${AUTHORIZATION_URI}
            token-uri: ${TOKEN_URI}
            user-info-uri: ${USER_INFO_URI}
            user-name-attribute: id
jwt:
  issuer: bbanglebbangle
  secret_key: bbangleOven
