### local 설정 파일

server:
  port: ${SERVER_PORT}
spring:
  config:
    import: optional:classpath:.env[.properties]
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      maxRequestSize: ${MAX_REQUEST_SIZE}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
        default_batch_fetch_size: 500
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 10780000
      maximum-pool-size: 5
      minimum-idle: 5
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  flyway:
    locations: classpath:/flyway
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    fail-on-missing-locations: true

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      end-point: ${S3_ENDPOINT}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false
    file-path:
      recommend-board-data-file-url: ${RECOMMEND_BOARD_DATA_FILE_URL}
      recommend-board-resource-data-url: ${RECOMMEND_BOARD_RESOURCE_DATA_URL}
logging:
  level:
    com.bbangle: DEBUG
    com.zaxxer.hikari: DEBUG

bucket:
  domain: ${BUCKET_DOMAIN}
cdn:
  domain: ${CDN_DOMAIN}
fcm:
  key-path: ${FCM_KEY_PATH}
  api-url: ${FCM_API_URL}
  google-authentication-url: ${FCM_GOOGLE_AUTHENTICATION_URL}
slack:
  webhook-url: ${SLACK_WEBHOOK_URL}

app:
  cookie:
    domain: ${COOKIE_DOMAIN}