### local 설정 파일

server:
  port: ${SERVER_PORT}
spring:
  config:
    import: optional:classpath:.env[.properties]
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      maxRequestSize: ${MAX_REQUEST_SIZE}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MariaDBDialect
        default_batch_fetch_size: 500
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      max-lifetime: 10780000
      maximum-pool-size: 5
      minimum-idle: 5
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  flyway:
    locations: classpath:/flyway
    enabled: true
    baseline-on-migrate: true
    baseline-version: 1
    fail-on-missing-locations: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-name: kakao
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_REDIRECT_URI}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
          google:
            client-name: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${OAUTH2_REDIRECT_URI}
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

management:
  server:
    port: ${MANAGEMENT_SERVER_PORT}
  endpoints:
    web:
      exposure:
        include: health, prometheus

  prometheus:
    metrics:
      export:
        enabled: true

oauth2:
  # OAuth2 로그인 인증 후 리다이렉트할 URL 및 도메인을 화이트리스트 방식으로 관리
  redirect:
    success: ${OAUTH2_REDIRECT_SUCCESS}
    error: ${OAUTH2_REDIRECT_ERROR}
  domain:
    local: ${LOCAL_DOMAIN}
    seller: ${SELLER_DOMAIN}
    customer: ${CUSTOMER_DOMAIN}

jwt:
  issuer: ${JWT_ISSUER}
  secret_key: ${JWT_SECRET}
cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
      end-point: ${S3_ENDPOINT}
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ${AWS_REGION}
      auto: false
    stack:
      auto: false
    file-path:
      recommend-board-data-file-url: ${RECOMMEND_BOARD_DATA_FILE_URL}
      recommend-board-resource-data-url: ${RECOMMEND_BOARD_RESOURCE_DATA_URL}
logging:
  config: classpath:logback/local.xml
  file:
    path: ${LOG_PATH}

logstash:
  destination: ${LOGSTASH_DESTINATION}

bucket:
  domain: ${BUCKET_DOMAIN}
cdn:
  domain: ${CDN_DOMAIN}
fcm:
  key-path: ${FCM_KEY_PATH}
  api-url: ${FCM_API_URL}
  google-authentication-url: ${FCM_GOOGLE_AUTHENTICATION_URL}
slack:
  webhook-url: ${SLACK_WEBHOOK_URL}

app:
  cookie:
    domain: ${COOKIE_DOMAIN}

encryption:
  aes:
    secret-key: ${AES_SECRET_KEY}

link-tracking:
  destinations: http://localhost:3000