name: Dev 서버 CD 파이프라인 (개발 서버)

on:
  workflow_dispatch: 
  push:
    branches:
      - dev
      - swagger-login-fix

jobs:
  job:
    name: Deploy dev API
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: 체크 아웃
        uses: actions/checkout@v3

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: application.yml 정보 넣기
        run: |
          mkdir -p src/main/resources
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
          find src

      - name: Setup Firebase service key
        run: |
          mkdir -p firebase
          echo "${{ secrets.FIREBASE_SERVICE_KEY_BASE64_ENCODE }}" | base64 --decode > firebase/firebase_service_key.json
          find src
          cat firebase/firebase_service_key.json

      - name: Copy Firebase service key to Docker container
        run: |
          docker cp firebase/firebase_service_key.json server:/firebase/firebase_service_key.json

      - name: build 실행
        run: ./gradlew build -x test

      - name: Prepare Files
        run: |
          cp build/libs/Bbangle-0.0.1-SNAPSHOT.jar ./

      - name: 기존 서버 내 jar 파일 삭제
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_AWS_SSH_HOST }}
          username: ${{ secrets.DEV_AWS_SSH_USERNAME }}
          key: ${{ secrets.DEV_AWS_SSH_KEY }}
          port: ${{ secrets.DEV_AWS_SSH_PORT }}
          source: "firebase/firebase_service_key.json"
          target: "~/firebase/"

      - name: jar 파일 운영 서버 전송
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          port: ${{ secrets.DEV_SSH_PORT }}
          source: "Bbangle-0.0.1-SNAPSHOT.jar"
          target: "~"

      - name: 전송된 jar 파일로 서버 재구동
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          username: ${{ secrets.DEV_SSH_USERNAME }}
          password: ${{ secrets.DEV_SSH_PASSWORD }}
          port: ${{ secrets.DEV_SSH_PORT }}
          script: |
            chmod +x deploy.sh
            ./deploy.sh
