name: Measure coverage
on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  build:
    steps:
      - name: 테스트 커버리지를 PR에 코멘트로 등록합니다
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{ github.workspace }}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 10
          min-coverage-changed-files: 10
          skip-if-no-changes: true
          update-comment: true
          title: Code Coverage
